package com.dbmi.demos.quiz.model;

/**
 * TODO Autogenerated javadoc comment.
 */
public class QuizException extends Exception {

   private static final long serialVersionUID = 78415623987L;

   public QuizException(String theMessage) {
      super(theMessage);
   }

} // CLASS
